name: oakink
channels:
  - defaults
dependencies:
  - python=3.8.11
  - pip
  - setuptools
  - cython
  - nvidia::cudatoolkit=11.1
  - numpy
  - pillow
  - pytorch::pytorch=1.9.1
  - bottler::nvidiacub
  - pytorch::torchaudio=0.9.1
  - pytorch::torchvision=0.10.1
